### PR TITLE
Resetting old data of first post

### PR DESCRIPTION
**Pull request by coderNik**
Data of first post was applying for new posts too, this was not resetting, which caused repeat meta data

### CODE REVIEW

**Comment by Hube2** [comment]
I hadn't noticed this, but since this is a recursive function where you put the reset will empty the results on each recursion. I'm not sure there it should go, I'll need to look at it closer.

**Comment by Hube2** [comment]
Is this duplication of meta data happening during the check and repair when it's doing a foreach on posts or is it happening at other times as well?

**Comment by Hube2** [comment]
I've just committed and update and I've put the data array reset at the beginning of the `update_post` function in the same file. This will reset the data before each post that needs to be updated. Let me know if there's still an issue with it this way.

**Comment by coderNik** [comment]
Duplication of meta data was happening during check and repair only.. and thanks for commit..

**Pull request closed without merging**
